---
title: "Examples"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{examples}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```
```{r echo=FALSE, fig.width=12, fig.height=6}
    library(ggplot2)
    library(patchwork)
    library(geometria)

    set.seed(555)
    x1 <- rnorm(7000); y1 <- rnorm(7000)
    idx1 <- C.chull(x1, y1, "quick", "indices")
    df1 <- data.frame(x=x1, y=y1)
    hull1 <- rbind(df1[idx1,], df1[idx1[1],])

    p1 <- ggplot(df1, aes(x, y)) +
    geom_point(size=0.5, color="gray60") +
    geom_polygon(data=hull1, fill=NA, color="red", linewidth=1) +
    geom_point(data=hull1, color="red", size=2) +
    coord_equal() +
    theme_minimal() +
    ggtitle("rnorm(7000)")

    x2 <- rbeta(7000, 3, 3); y2 <- rbeta(7000, 3, 3)
    idx2 <- C.chull(x2, y2, "quick", "indices")
    df2 <- data.frame(x=x2, y=y2)
    hull2 <- rbind(df2[idx2,], df2[idx2[1],])

    p2 <- ggplot(df2, aes(x, y)) +
    geom_point(size=0.5, color="gray60") +
    geom_polygon(data=hull2, fill=NA, color="red", linewidth=1) +
    geom_point(data=hull2, color="red", size=2) +
    coord_equal() +
    theme_minimal() +
    ggtitle("rbeta(7000, 3, 3)")

    p1 + p2
```

